import { useLibraryStore } from "../store/library";
import { useSetStore } from "../store/set";
import type { Track } from "../types";

export const DEMO_TRACKS: Record<string, Track> = {
  t1: { id:"t1", path:"/music/Teach Me.mp3", filename:"Teach Me.mp3", title:"Teach Me", artist:"Adam Beyer", album:"Drumcode", genre:"Techno", year:2023, duration:418, bpm:132.0, bpm_confidence:0.95, key_camelot:"8A", key_standard:"Am", energy:5, vocal:"hook", mood_tags:["peak","dark","percussive"], structure:{ intro_end:32, first_drop:64, break_start:210, break_end:242, outro_start:370, sections:[] }, cue_points:[{id:"c1",type:"entry",position:60,label:"Entry",color:"#22c55e"},{id:"c2",type:"drop",position:64,label:"Drop",color:"#f97316"},{id:"c3",type:"break",position:210,label:"Break",color:"#3b82f6"},{id:"c4",type:"exit",position:370,label:"Exit",color:"#ef4444"}], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t2: { id:"t2", path:"/music/Doppler.flac", filename:"Doppler.flac", title:"Doppler", artist:"Charlotte de Witte", album:"Return To Nowhere", genre:"Techno", year:2022, duration:392, bpm:135.5, bpm_confidence:0.97, key_camelot:"9A", key_standard:"Em", energy:5, vocal:"none", mood_tags:["peak","dark","hypnotic"], structure:{ intro_end:28, first_drop:56, break_start:196, break_end:224, outro_start:350, sections:[] }, cue_points:[{id:"c5",type:"entry",position:52,label:"Entry",color:"#22c55e"},{id:"c6",type:"drop",position:56,label:"Drop",color:"#f97316"}], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t3: { id:"t3", path:"/music/Exhale.mp3", filename:"Exhale.mp3", title:"Exhale", artist:"Amelie Lens", album:"Exhale EP", genre:"Techno", year:2021, duration:445, bpm:140.0, bpm_confidence:0.92, key_camelot:"4A", key_standard:"Fm", energy:4, vocal:"none", mood_tags:["peak","dark","rolling"], structure:null, cue_points:[], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t4: { id:"t4", path:"/music/Barbarella.mp3", filename:"Barbarella.mp3", title:"Barbarella", artist:"Sven Väth", album:"An Accident In Paradise", genre:"Techno", year:2020, duration:380, bpm:128.0, bpm_confidence:0.89, key_camelot:"7B", key_standard:"F", energy:3, vocal:"full", mood_tags:["rolling","uplifting","vocal-heavy"], structure:null, cue_points:[], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t5: { id:"t5", path:"/music/Black Metal.wav", filename:"Black Metal.wav", title:"Black Metal", artist:"Rebekah", album:"Rebekah EP", genre:"Techno", year:2023, duration:467, bpm:138.0, bpm_confidence:0.94, key_camelot:"11A", key_standard:"Bbm", energy:5, vocal:"none", mood_tags:["peak","dark","percussive"], structure:null, cue_points:[], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t6: { id:"t6", path:"/music/Getting Me Down.mp3", filename:"Getting Me Down.mp3", title:"Getting Me Down", artist:"Blawan", album:"Fram", genre:"Industrial Techno", year:2022, duration:356, bpm:142.0, bpm_confidence:0.91, key_camelot:"3A", key_standard:"Ebm", energy:4, vocal:"spoken", mood_tags:["dark","hypnotic"], structure:null, cue_points:[], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t7: { id:"t7", path:"/music/Discipline.flac", filename:"Discipline.flac", title:"Discipline", artist:"Dax J", album:"Discipline LP", genre:"Techno", year:2021, duration:398, bpm:134.0, bpm_confidence:0.96, key_camelot:"6A", key_standard:"Gm", energy:4, vocal:"none", mood_tags:["dark","rolling","hypnotic"], structure:null, cue_points:[], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t8: { id:"t8", path:"/music/Spastik.mp3", filename:"Spastik.mp3", title:"Spastik", artist:"Richie Hawtin", album:"Plastikman", genre:"Minimal Techno", year:2019, duration:520, bpm:126.0, bpm_confidence:0.88, key_camelot:"2A", key_standard:"Dbm", energy:3, vocal:"none", mood_tags:["hypnotic","rolling","instrumental"], structure:null, cue_points:[], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t9: { id:"t9", path:"/music/Unreleased.wav", filename:"Unreleased Dub.wav", title:"Unreleased Dub", artist:"Unknown Artist", album:"", genre:"Techno", year:null, duration:361, bpm:null, bpm_confidence:null, key_camelot:null, key_standard:null, energy:null, vocal:null, mood_tags:[], structure:null, cue_points:[], analyzed:false, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
  t10: { id:"t10", path:"/music/Fade.mp3", filename:"Fade.mp3", title:"Fade To Mind", artist:"Surgeon", album:"Force + Form", genre:"Techno", year:2022, duration:402, bpm:136.0, bpm_confidence:0.93, key_camelot:"5A", key_standard:"Cm", energy:4, vocal:"none", mood_tags:["dark","hypnotic"], structure:null, cue_points:[], analyzed:true, analyzing:false, analysis_error:null, custom_energy:null, custom_tags:[], waveform_peaks:null, sub_bass_energy:null, bass_energy:null, folder_id:null },
};

export function injectDemoData() {
  useLibraryStore.setState({ tracks: DEMO_TRACKS });
  useSetStore.getState().buildSet(
    { template: "peak", duration_minutes: 60, available_tracks: Object.values(DEMO_TRACKS) },
    Object.values(DEMO_TRACKS)
  );
}
